In [11]:
import numpy as np
import time as t

size = 1_000_000

lst1 = list(range(size))
lst2 = list(range(size))

start = t.time()
add = [x+y for x,y in zip(lst1,lst2)]  #list comprehension
end = t.time()
print(add[0:100])
print(end-start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]
0.04553389549255371


In [12]:
size = 1_000_000

lst1 = np.array(list(range(size)))
lst2 = np.array(list(range(size)))

start = t.time()
add = lst1+lst2
end = t.time()
print(add[0:100])
print(end-start)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]
0.010467052459716797


In [13]:
print(type(add))
print(add.shape)   #shows dimension of the numpy array

<class 'numpy.ndarray'>
(1000000,)


In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [18]:
np.eye(4)  #generate an identity matrix of order 4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.arange(1, 10, 2) # [1, 3, 5, 7, 9] (like range)

array([1, 3, 5, 7, 9])

In [20]:
np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

In [22]:
print("Shape:", arr.shape)

Shape: (2, 3)


In [23]:
print("Size:", arr.size)

Size: 6


In [24]:
print("Dimensions:", arr.ndim)  #2d array

Dimensions: 2


In [25]:
print("Data type:", arr.dtype)

Data type: int64


In [26]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

In [27]:
print(arr3D[1: 0 :]) 

[]


In [28]:
arr2D = np.array([[1, 2, 3], 
                 [4, 5, 6]])

In [33]:
arr2D[:, 1] = 0

In [34]:
arr2D

array([[1, 0, 3],
       [4, 0, 6]])

In [36]:
arr = np.array([1,2,4,5,6],dtype = "float64")

In [37]:
arr

array([1., 2., 4., 5., 6.])

In [39]:
#broadcasting
arr1 = np.array([1,2,3,4])
arr2 = np.array([7,8,9])


array([ 8, 10, 12])

In [41]:
ans = arr1+arr2
ans

array([ 8, 10, 12])

In [42]:
ans = arr1+5
ans

array([6, 7, 8])

In [55]:
arr3 = np.array([[10,20,30,1],[40,50,60,2]])
arr1 = np.array([1,2,3,4])
ans = arr3+arr1
ans

array([[11, 22, 33,  5],
       [41, 52, 63,  6]])

In [57]:
np.diff(arr1)

array([1, 1, 1])

In [58]:
arr4 = np.linspace(0, 10, 5)
arr4

array([ 0. ,  2.5,  5. ,  7.5, 10. ])